const KEY="tims-calculators-countdowns-v1";
function parseDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v);return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3])):null}
function todayUTC(){const n=new Date();return new Date(Date.UTC(n.getFullYear(),n.getMonth(),n.getDate()))}
function daysBetween(a,b){return Math.round((b-a)/86400000)}
function nice(d){return d.toLocaleDateString("en-US",{timeZone:"UTC",weekday:"long",year:"numeric",month:"long",day:"numeric"})}
function weekdays(a,b){let n=0,dir=b>=a?1:-1,d=new Date(a);while((dir>0&&d<b)||(dir<0&&d>b)){d.setUTCDate(d.getUTCDate()+dir);const w=d.getUTCDay();if(w!==0&&w!==6)n+=dir}return n}
function monthDayDiff(a,b){let sign=b>=a?1:-1,start=sign>0?new Date(a):new Date(b),end=sign>0?new Date(b):new Date(a);let months=(end.getUTCFullYear()-start.getUTCFullYear())*12+end.getUTCMonth()-start.getUTCMonth();let anchor=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+months,start.getUTCDate()));if(anchor>end){months--;anchor=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+months,start.getUTCDate()))}return {months,days:daysBetween(anchor,end)}}
export function initDaysUntil(){
const name=document.querySelector("#eventName"),date=document.querySelector("#eventDate"),list=document.querySelector("#savedEvents"),empty=document.querySelector("#daysEmpty");let events=[];try{events=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{events=[]}
function persist(){localStorage.setItem(KEY,JSON.stringify(events))}
function feature(ev){const t=todayUTC(),d=parseDate(ev.date);if(!d)return;const n=daysBetween(t,d),abs=Math.abs(n),md=monthDayDiff(t,d);document.querySelector("#countDirection").textContent=n>=0?"DAYS UNTIL":"DAYS SINCE";document.querySelector("#daysBig").textContent=abs;document.querySelector("#featuredName").textContent=ev.name;document.querySelector("#featuredDate").textContent=nice(d);document.querySelector("#weeksDays").textContent=`${Math.floor(abs/7)}w ${abs%7}d`;document.querySelector("#monthsDays").textContent=`${md.months}m ${md.days}d`;document.querySelector("#weekdays").textContent=Math.abs(weekdays(t,d)).toLocaleString();document.querySelector("#dateStats").classList.remove("hidden")}
function render(){const t=todayUTC();events.sort((a,b)=>{const da=parseDate(a.date),db=parseDate(b.date);const aa=daysBetween(t,da),bb=daysBetween(t,db);return (aa<0)-(bb<0)||Math.abs(aa)-Math.abs(bb)});list.innerHTML="";empty.classList.toggle("hidden",events.length>0);events.forEach(ev=>{const d=parseDate(ev.date),n=daysBetween(t,d);const row=document.createElement("div");row.className="saved-event";row.innerHTML=`<button class="saved-main" type="button"><b>${escapeHtml(ev.name)}</b><small>${nice(d)}</small></button><span class="saved-days">${Math.abs(n)} ${Math.abs(n)===1?"day":"days"}</span><div class="event-actions"><button class="edit" type="button">Edit</button><button class="delete" type="button">Delete</button></div>`;row.querySelector(".saved-main").addEventListener("click",()=>feature(ev));row.querySelector(".edit").addEventListener("click",()=>{name.value=ev.name;date.value=ev.date;events=events.filter(x=>x.id!==ev.id);persist();render();name.focus()});row.querySelector(".delete").addEventListener("click",()=>{events=events.filter(x=>x.id!==ev.id);persist();render()});list.appendChild(row)});if(events.length)feature(events[0])}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
document.querySelector("#saveEvent").addEventListener("click",()=>{const nm=name.value.trim(),d=parseDate(date.value);if(!nm||!d){alert("Enter an event name and date.");return}events.push({id:Date.now().toString(36),name:nm,date:date.value});persist();name.value="";date.value="";render()});render()}
